services:
  environment:
    build: ./environment
    image: rl-g4/environment
    container_name: environment
    environment:
      - GRID_WIDTH=10
      - GRID_HEIGHT=10

  agent:
    build: ./agent
    image: rl-g4/agent
    container_name: agent
    depends_on:
      - environment
    environment:
      - ENV_URL=http://environment:5000
